import type { Metadata } from "next";
import { brand } from "@/config/brand";
import { absoluteUrl } from "./urls";

/**
 * Open Graph locale. The spec wants `language_TERRITORY`, and `419` is a UN M.49 region
 * code, not an ISO 3166 territory, so `es_419` is rejected by the consumers that validate
 * it. `es_LA` is the code those platforms publish for Latin American Spanish, and it is the
 * honest one here: `es_ES` would claim Spain vocabulary the content rules forbid, and
 * `es_AR` would narrow a pan-LATAM product to one country. `<html lang>` stays `es-419`,
 * which is correct BCP-47 and is what assistive technology reads.
 */
export const OG_LOCALE = "es_LA";

/**
 * The site-wide card, generated by `src/app/opengraph-image.tsx`. It has to be named
 * explicitly: Next only inherits a parent segment's image file while the child sets no
 * `openGraph` of its own, and every page here sets one to get a canonical `og:url`.
 */
const DEFAULT_OG_IMAGE = "/opengraph-image";

function image(path: string, alt: string) {
  return { url: absoluteUrl(path), width: 1200, height: 630, alt, type: "image/png" };
}

export interface PageMetadataInput {
  /** Route path, e.g. `/precios`. Becomes the canonical URL and `og:url`. */
  path: string;
  /** Page title. The root template appends the short brand name for `<title>`. */
  title: string;
  description: string;
  /** Headline used in the card; defaults to `title · shortName`. */
  socialTitle?: string;
  type?: "website" | "article" | "profile";
  /** Pages that must not be indexed but still deserve a share card. */
  noIndex?: boolean;
  /** Skip the `%s · shortName` title template (the landing page already names the product). */
  absoluteTitle?: boolean;
  /**
   * Share image. Defaults to the site-wide card. Pass `null` when the route has its own
   * `opengraph-image` file in the same segment, which Next merges by itself.
   */
  imagePath?: string | null;
}

/**
 * One place that builds canonical + Open Graph + Twitter card tags, so no route can
 * ship half a card. The image itself comes from the `opengraph-image` file convention,
 * which Next resolves against `metadataBase` (set in the root layout).
 */
export function buildPageMetadata({
  path,
  title,
  description,
  socialTitle,
  type = "website",
  noIndex = false,
  absoluteTitle = false,
  imagePath = DEFAULT_OG_IMAGE,
}: PageMetadataInput): Metadata {
  const url = absoluteUrl(path);
  const headline = socialTitle ?? (absoluteTitle ? title : `${title} · ${brand.shortName}`);
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    ...(noIndex ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      type,
      url,
      siteName: brand.productName,
      locale: OG_LOCALE,
      title: headline,
      description,
      ...(imagePath ? { images: [image(imagePath, headline)] } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: headline,
      description,
      ...(imagePath ? { images: [image(imagePath, headline)] } : {}),
    },
  };
}
