"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { RefreshCw } from "lucide-react";
import { useFormatter, useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { createPromoCodeAction } from "@/lib/admin/actions";
import { accessEndsAt } from "@/lib/payments/access-grants";
import { generatePromoCode } from "@/lib/payments/promo-code";

/**
 * Creating a scholarship or discount code.
 *
 * Two things the owner asked for (items 18 and 19):
 *   - the code is generated by default, from an alphabet with no O/0 or I/1 confusion, because a
 *     code is read out loud and retyped; a custom code is still allowed for a campaign name;
 *   - "días de acceso" is the only duration input. What it implies — the date the access would end
 *     for someone redeeming today — is derived and shown live, and is a different fact from the
 *     date the code itself stops being redeemable, which now says so in its own label.
 */
export function PromoForm() {
  const t = useTranslations("admin.promos.form");
  const format = useFormatter();
  const router = useRouter();
  const [kind, setKind] = useState<"scholarship" | "discount">("scholarship");
  const [custom, setCustom] = useState(false);
  const [code, setCode] = useState("");
  const [days, setDays] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const [createdCode, setCreatedCode] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();

  const numericDays = days.trim() === "" ? null : Number(days);
  const endsOn =
    numericDays !== null && Number.isFinite(numericDays) && numericDays > 0
      ? accessEndsAt(numericDays)
      : null;

  return (
    <form
      className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"
      onSubmit={(e) => {
        e.preventDefault();
        const form = e.currentTarget;
        const data = Object.fromEntries(new FormData(form).entries());
        startTransition(async () => {
          const r = await createPromoCodeAction({ ...data, code: custom ? code : "" });
          setMessage(r.ok ? t("done") : t(`errors.${r.error}` as "errors.unknown"));
          setCreatedCode(r.ok ? r.data.code : null);
          if (r.ok) {
            form.reset();
            setCode("");
            setDays("");
            setCustom(false);
            router.refresh();
          }
        });
      }}
    >
      <div className="sm:col-span-2 lg:col-span-3">
        <label className="flex items-center gap-2 text-sm">
          <input
            type="checkbox"
            className="size-4"
            checked={custom}
            onChange={(e) => {
              setCustom(e.target.checked);
              if (e.target.checked && !code) setCode(generatePromoCode());
            }}
          />
          {t("customCode")}
        </label>
        <p className="text-muted mt-1 text-xs">
          {custom ? t("customCodeHint") : t("generatedHint")}
        </p>
      </div>

      {custom ? (
        <Field id="promo-code" label={t("code")} hint={t("codeHint")}>
          <div className="flex gap-2">
            <input
              id="promo-code"
              name="code"
              className="input font-mono uppercase"
              required
              minLength={4}
              maxLength={40}
              pattern="[A-Za-z0-9-]+"
              value={code}
              onChange={(e) => setCode(e.target.value)}
            />
            <Button
              type="button"
              variant="secondary"
              onClick={() => setCode(generatePromoCode())}
              aria-label={t("regenerate")}
            >
              <RefreshCw aria-hidden="true" className="size-4" />
            </Button>
          </div>
        </Field>
      ) : null}

      <Field id="promo-kind" label={t("kind")}>
        <select
          id="promo-kind"
          name="kind"
          className="input"
          value={kind}
          onChange={(e) => setKind(e.target.value as "scholarship" | "discount")}
        >
          <option value="scholarship">{t("kinds.scholarship")}</option>
          <option value="discount">{t("kinds.discount")}</option>
        </select>
      </Field>
      {kind === "scholarship" ? (
        <Field
          id="promo-days"
          label={t("accessDays")}
          hint={
            endsOn
              ? t("accessEndsOn", { date: format.dateTime(endsOn, { dateStyle: "long" }) })
              : t("accessDaysHint")
          }
        >
          <input
            id="promo-days"
            name="accessDays"
            type="number"
            className="input"
            min={1}
            max={3650}
            required
            value={days}
            onChange={(e) => setDays(e.target.value)}
          />
        </Field>
      ) : (
        <Field id="promo-discount" label={t("discountPercent")}>
          <input
            id="promo-discount"
            name="discountPercent"
            type="number"
            className="input"
            min={1}
            max={100}
            required
          />
        </Field>
      )}
      <Field id="promo-max" label={t("maxRedemptions")} hint={t("maxHint")}>
        <input id="promo-max" name="maxRedemptions" type="number" className="input" min={1} />
      </Field>
      <Field id="promo-expires" label={t("expiresAt")} hint={t("expiresHint")}>
        <input id="promo-expires" name="expiresAt" type="date" className="input" />
      </Field>
      <Field id="promo-note" label={t("note")}>
        <input id="promo-note" name="note" className="input" maxLength={300} />
      </Field>
      <div className="flex flex-wrap items-center gap-3 sm:col-span-2 lg:col-span-3">
        <Button type="submit" disabled={pending}>
          {t("submit")}
        </Button>
        <p role="status" aria-live="polite" className="text-sm">
          {message}
          {createdCode ? (
            <>
              {" "}
              <span className="font-mono font-semibold">{createdCode}</span>
            </>
          ) : null}
        </p>
      </div>
    </form>
  );
}
