/**
 * Builds supabase/seed/0002_content.sql from the validated content registry.
 * Idempotent upserts keyed by slug; parents resolved with subselects so ids stay stable.
 * Usage: npm run content:build   (CI fails if the committed seed drifts from the source)
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadContent } from "../src/content/load";
import { products } from "../src/config/pricing";

const loaded = loadContent();
if (loaded.issues.length) {
  console.error("content:build — fix content:validate issues first");
  process.exit(1);
}

let tagCounter = 0;
/** Dollar-quotes any text safely (tag chosen so it never appears inside the body). */
function q(text: string | null | undefined): string {
  if (text === null || text === undefined) return "null";
  let tag = `c${tagCounter++}`;
  while (text.includes(`$${tag}$`)) tag = `c${tagCounter++}`;
  return `$${tag}$${text}$${tag}$`;
}
const j = (value: unknown) => `${q(JSON.stringify(value))}::jsonb`;
const arr = (values: string[]) => `array[${values.map((v) => q(v)).join(",")}]::text[]`;
const b = (v: boolean) => (v ? "true" : "false");
const sec = (slug: string) => `(select id from public.sections where slug = ${q(slug)})`;
const les = (slug: string) => `(select id from public.lessons where slug = ${q(slug)})`;
const ds = (slug: string) => `(select id from public.datasets where slug = ${q(slug)})`;
const exr = (slug: string) => `(select id from public.exercises where slug = ${q(slug)})`;

const out: string[] = [
  "-- Generated by scripts/content-build.ts from src/content. Do not edit by hand.",
  "begin;",
];

for (const c of loaded.courses) {
  out.push(`insert into public.courses (slug, title, description, sort_order, is_published)
values (${q(c.slug)}, ${q(c.title)}, ${q(c.description)}, ${c.sort_order}, ${b(c.is_published)})
on conflict (slug) do update set title = excluded.title, description = excluded.description, sort_order = excluded.sort_order, is_published = excluded.is_published;`);
}

// Sections: insert without requires first (self-reference), then set requires.
for (const s of loaded.sections) {
  out.push(`insert into public.sections (course_id, slug, number, level, title, summary, objectives, is_free_theory, is_published, certificate_slug)
values ((select id from public.courses where slug = ${q(s.course)}), ${q(s.slug)}, ${s.number}, ${q(s.level)}, ${q(s.title)}, ${q(s.summary)}, ${j(s.objectives)}, ${b(s.is_free_theory)}, ${b(s.is_published)}, ${q(s.certificate)})
on conflict (slug) do update set number = excluded.number, level = excluded.level, title = excluded.title, summary = excluded.summary, objectives = excluded.objectives, is_free_theory = excluded.is_free_theory, is_published = excluded.is_published, certificate_slug = excluded.certificate_slug;`);
}
for (const s of loaded.sections) {
  out.push(
    `update public.sections set requires_section_id = ${s.requires ? sec(s.requires) : "null"} where slug = ${q(s.slug)};`,
  );
}

for (const d of loaded.datasets) {
  out.push(`insert into public.datasets (slug, version, title, domain, description, is_active)
values (${q(d.slug)}, ${d.version}, ${q(d.title)}, ${q(d.domain)}, ${q(d.description)}, ${b(d.is_active)})
on conflict (slug) do update set version = excluded.version, title = excluded.title, domain = excluded.domain, description = excluded.description, is_active = excluded.is_active;`);
  d.tables.forEach((t, ti) => {
    out.push(`insert into public.dataset_tables (dataset_id, name, description, sort_order)
values (${ds(d.slug)}, ${q(t.name)}, ${q(t.description)}, ${ti})
on conflict (dataset_id, name) do update set description = excluded.description, sort_order = excluded.sort_order;`);
    t.columns.forEach((c, ci) => {
      out.push(`insert into public.dataset_columns (table_id, name, data_type, description, is_pk, fk_ref, sort_order)
values ((select id from public.dataset_tables where dataset_id = ${ds(d.slug)} and name = ${q(t.name)}), ${q(c.name)}, ${q(c.data_type)}, ${q(c.description)}, ${b(c.is_pk)}, ${q(c.fk_ref)}, ${ci})
on conflict (table_id, name) do update set data_type = excluded.data_type, description = excluded.description, is_pk = excluded.is_pk, fk_ref = excluded.fk_ref, sort_order = excluded.sort_order;`);
    });
  });
}

for (const l of loaded.lessons) {
  out.push(`insert into public.lessons (section_id, slug, kind, title, sort_order, estimated_minutes, body_md, ref_slug, dataset_id, is_free, is_published)
values (${sec(l.section)}, ${q(l.slug)}, ${q(l.kind)}, ${q(l.title)}, ${l.sort_order}, ${l.estimated_minutes}, ${q(l.body_md)}, ${q(l.ref)}, ${l.dataset ? ds(l.dataset) : "null"}, ${b(l.is_free)}, ${b(l.is_published)})
on conflict (slug) do update set section_id = excluded.section_id, kind = excluded.kind, title = excluded.title, sort_order = excluded.sort_order, estimated_minutes = excluded.estimated_minutes, body_md = excluded.body_md, ref_slug = excluded.ref_slug, dataset_id = excluded.dataset_id, is_free = excluded.is_free, is_published = excluded.is_published;`);
}
for (const l of loaded.lessons) {
  out.push(`delete from public.lesson_prerequisites where lesson_id = ${les(l.slug)};`);
  for (const p of l.prerequisites) {
    out.push(
      `insert into public.lesson_prerequisites (lesson_id, requires_lesson_id) values (${les(l.slug)}, ${les(p)}) on conflict do nothing;`,
    );
  }
}

for (const qn of loaded.questions) {
  out.push(`insert into public.theory_questions (section_id, lesson_id, slug, type, difficulty, topic, prompt_md, code_md, explanation_md, answer, pairs, tags, estimated_seconds, is_published)
values (${sec(qn.section)}, ${les(qn.lesson)}, ${q(qn.slug)}, ${q(qn.type)}, ${q(qn.difficulty)}, ${q(qn.topic)}, ${q(qn.prompt_md)}, ${q(qn.code_md)}, ${q(qn.explanation_md)}, ${qn.answer ? j(qn.answer) : "null"}, ${qn.pairs ? j(qn.pairs) : "null"}, ${arr(qn.tags)}, ${qn.estimated_seconds}, ${b(qn.is_published)})
on conflict (slug) do update set section_id = excluded.section_id, lesson_id = excluded.lesson_id, type = excluded.type, difficulty = excluded.difficulty, topic = excluded.topic, prompt_md = excluded.prompt_md, code_md = excluded.code_md, explanation_md = excluded.explanation_md, answer = excluded.answer, pairs = excluded.pairs, tags = excluded.tags, estimated_seconds = excluded.estimated_seconds, is_published = excluded.is_published;`);
  const qid = `(select id from public.theory_questions where slug = ${q(qn.slug)})`;
  out.push(`delete from public.question_options where question_id = ${qid};`);
  (qn.options ?? []).forEach((o, oi) => {
    out.push(`insert into public.question_options (question_id, key, body_md, is_correct, why_incorrect_md, sort_order)
values (${qid}, ${q(o.key)}, ${q(o.body_md)}, ${b(o.is_correct)}, ${q(o.why_incorrect_md)}, ${oi});`);
  });
}

for (const e of loaded.exercises) {
  out.push(`insert into public.exercises (lesson_id, section_id, slug, title, scenario_md, business_question_md, learning_objective, difficulty, estimated_minutes, concepts, tables_used, dataset_id, dataset_version, theory_ref_slug, allowed_statements, expected_columns, validation_rules, common_mistakes, expert_explanation_md, improvement_feedback, reward_config, solution_unlock, is_published)
values ((select id from public.lessons where kind in ('exercise','challenge') and ref_slug = ${q(e.slug)}), ${sec(e.section)}, ${q(e.slug)}, ${q(e.title)}, ${q(e.scenario_md)}, ${q(e.business_question_md)}, ${q(e.learning_objective)}, ${q(e.difficulty)}, ${e.estimated_minutes}, ${arr(e.concepts)}, ${arr(e.tables_used)}, ${ds(e.dataset.slug)}, ${e.dataset.version}, ${q(e.theory_ref)}, ${arr(e.allowed_statements)}, ${j(e.expected_columns)}, ${j(e.validation_rules)}, ${j(e.common_mistakes)}, ${q(e.expert_explanation_md)}, ${j(e.improvement_feedback)}, ${j(e.reward)}, ${j(e.solution_unlock)}, ${b(e.is_published)})
on conflict (slug) do update set lesson_id = excluded.lesson_id, section_id = excluded.section_id, title = excluded.title, scenario_md = excluded.scenario_md, business_question_md = excluded.business_question_md, learning_objective = excluded.learning_objective, difficulty = excluded.difficulty, estimated_minutes = excluded.estimated_minutes, concepts = excluded.concepts, tables_used = excluded.tables_used, dataset_id = excluded.dataset_id, dataset_version = excluded.dataset_version, theory_ref_slug = excluded.theory_ref_slug, allowed_statements = excluded.allowed_statements, expected_columns = excluded.expected_columns, validation_rules = excluded.validation_rules, common_mistakes = excluded.common_mistakes, expert_explanation_md = excluded.expert_explanation_md, improvement_feedback = excluded.improvement_feedback, reward_config = excluded.reward_config, solution_unlock = excluded.solution_unlock, is_published = excluded.is_published;`);
  out.push(`delete from public.exercise_solutions where exercise_id = ${exr(e.slug)};`);
  out.push(
    `insert into public.exercise_solutions (exercise_id, sql, is_reference, approach_label, sort_order) values (${exr(e.slug)}, ${q(e.reference_solution)}, true, 'reference', 0);`,
  );
  e.alternative_solutions.forEach((a, ai) => {
    out.push(
      `insert into public.exercise_solutions (exercise_id, sql, is_reference, approach_label, sort_order) values (${exr(e.slug)}, ${q(a.sql)}, false, ${q(a.label)}, ${ai + 1});`,
    );
  });
  for (const h of e.hints) {
    out.push(`insert into public.exercise_hints (exercise_id, level, body_md, coin_cost, xp_penalty_percent)
values (${exr(e.slug)}, ${h.level}, ${q(h.body_md)}, ${h.coin_cost}, ${h.xp_penalty_percent})
on conflict (exercise_id, level) do update set body_md = excluded.body_md, coin_cost = excluded.coin_cost, xp_penalty_percent = excluded.xp_penalty_percent;`);
  }
  out.push(`delete from public.exercise_prerequisites where exercise_id = ${exr(e.slug)};`);
  for (const p of e.prerequisites) {
    out.push(
      `insert into public.exercise_prerequisites (exercise_id, requires_exercise_id) values (${exr(e.slug)}, ${exr(p)}) on conflict do nothing;`,
    );
  }
}

// Products and prices come from src/config/pricing.ts (D-05, D-06); admins may adjust rows later.
for (const p of products) {
  out.push(`insert into public.products (slug, kind, title, description, access_days, is_active)
values (${q(p.slug)}, ${q(p.kind)}, ${q(p.title)}, ${q(p.description)}, ${p.accessDays === null ? "null" : p.accessDays}, ${b(p.isActive)})
on conflict (slug) do update set kind = excluded.kind, title = excluded.title, description = excluded.description, access_days = excluded.access_days, is_active = excluded.is_active;`);
  for (const pr of p.prices) {
    out.push(`insert into public.prices (product_id, provider, currency, amount_minor, country, interval, is_active)
values ((select id from public.products where slug = ${q(p.slug)}), ${q(pr.provider)}, ${q(pr.currency)}, ${pr.amountMinor}, ${pr.country ? q(pr.country) : "null"}, ${q(pr.interval)}, true)
on conflict (product_id, provider, currency, country) do update set amount_minor = excluded.amount_minor, interval = excluded.interval, is_active = true;`);
  }
}

out.push("commit;");
const target = join(process.cwd(), "supabase", "seed", "0002_content.sql");
writeFileSync(target, out.join("\n\n") + "\n");
console.log(`content:build — wrote ${target} (${out.length - 2} statements)`);
