/**
 * Executes every exercise's reference and alternative solutions against the exact dataset
 * snapshot (real PostgreSQL via PGlite, as the `learner` role), checks that alternatives are
 * equivalent under the exercise's own validation rules, and writes the expected results to
 * supabase/seed/0003_expected_results.sql. Also enforces that expected results fit the row cap.
 * Usage: npm run content:verify [-- exercise-slug]
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PGlite } from "@electric-sql/pglite";
import { limits } from "../src/config/limits";
import { loadContent } from "../src/content/load";
import { gateSql } from "../src/lib/sandbox/gate";
import { loadDatasetInto, runLearnerQuery } from "../sandbox-runtime/engine-core.mjs";
import { compareResults } from "../src/lib/validation/compare";
import type { SandboxResult } from "../src/lib/sandbox/types";

const only = process.argv[2];
const loaded = loadContent();
if (loaded.issues.length) {
  console.error("content:verify — fix content:validate issues first");
  process.exit(1);
}

const runLimits = {
  maxRows: limits.sandbox.maxRows,
  maxColumns: limits.sandbox.maxColumns,
  maxCellBytes: limits.sandbox.maxCellBytes,
};
const instances = new Map<string, Promise<PGlite>>();

async function engineFor(slug: string, version: number): Promise<PGlite> {
  const key = `${slug}@${version}`;
  let p = instances.get(key);
  if (!p) {
    p = (async () => {
      const dir = join(process.cwd(), "public", "datasets", slug, `v${version}`);
      if (!existsSync(join(dir, "manifest.json")))
        throw new Error(`dataset ${key} not built; run npm run datasets:build`);
      const manifest = JSON.parse(readFileSync(join(dir, "manifest.json"), "utf8")) as {
        schemaFile: string;
        tables: { name: string; file: string }[];
      };
      const pg = new PGlite();
      await pg.waitReady;
      await loadDatasetInto(pg, {
        schemaSql: readFileSync(join(dir, manifest.schemaFile), "utf8"),
        tables: manifest.tables.map((t) => ({
          name: t.name,
          csv: readFileSync(join(dir, t.file), "utf8"),
        })),
      });
      return pg;
    })();
    instances.set(key, p);
  }
  return p;
}

let tagCounter = 0;
function q(text: string): string {
  let tag = `v${tagCounter++}`;
  while (text.includes(`$${tag}$`)) tag = `v${tagCounter++}`;
  return `$${tag}$${text}$${tag}$`;
}

async function main() {
  const out: string[] = [
    "-- Generated by scripts/content-verify.ts. Do not edit by hand.",
    "begin;",
  ];
  let failures = 0;
  let verified = 0;

  for (const ex of loaded.exercises) {
    if (only && only !== ex.slug) continue;
    const label = `${ex.section}/${ex.slug}`;
    const gate = gateSql(ex.reference_solution, ex.allowed_statements);
    if (!gate.ok) {
      console.error(`  ✗ ${label}: reference solution rejected by gate: ${gate.message}`);
      failures++;
      continue;
    }
    const pg = await engineFor(ex.dataset.slug, ex.dataset.version);
    let reference: SandboxResult;
    try {
      reference = await runLearnerQuery(pg, ex.reference_solution, runLimits, true);
    } catch (err) {
      console.error(`  ✗ ${label}: reference solution failed: ${(err as Error).message}`);
      failures++;
      continue;
    }
    if (reference.truncated) {
      console.error(
        `  ✗ ${label}: expected result exceeds ${limits.sandbox.maxRows} rows; narrow the question`,
      );
      failures++;
      continue;
    }
    if (reference.rowCount === 0) {
      console.error(`  ✗ ${label}: reference solution returns no rows`);
      failures++;
      continue;
    }
    // Expected columns must match what the reference returns (names, order when it matters).
    const refNames = reference.columns.map((c) => c.name.toLowerCase());
    const wantNames = ex.expected_columns.map((c) => c.name.toLowerCase());
    if (refNames.join(",") !== wantNames.join(",")) {
      console.error(
        `  ✗ ${label}: reference columns [${refNames}] ≠ expected_columns [${wantNames}]`,
      );
      failures++;
      continue;
    }
    // Reference compared with itself must pass (sanity for the comparator config).
    const self = compareResults(reference, reference, ex.expected_columns, ex.validation_rules);
    if (!self.correct) {
      console.error(
        `  ✗ ${label}: reference does not validate against itself: ${JSON.stringify(self.findings)}`,
      );
      failures++;
      continue;
    }
    for (const alt of ex.alternative_solutions) {
      const g = gateSql(alt.sql, ex.allowed_statements);
      if (!g.ok) {
        console.error(`  ✗ ${label}: alternative "${alt.label}" rejected by gate: ${g.message}`);
        failures++;
        continue;
      }
      try {
        const altResult = await runLearnerQuery(pg, alt.sql, runLimits, true);
        const cmp = compareResults(altResult, reference, ex.expected_columns, ex.validation_rules);
        if (!cmp.correct) {
          console.error(
            `  ✗ ${label}: alternative "${alt.label}" is not equivalent: ${cmp.findings.map((f) => f.messageKey).join(", ")}`,
          );
          failures++;
        }
      } catch (err) {
        console.error(`  ✗ ${label}: alternative "${alt.label}" failed: ${(err as Error).message}`);
        failures++;
      }
    }
    verified++;
    console.log(
      `  ✓ ${label}: ${reference.rowCount} rows, ${reference.columns.length} columns, ${reference.durationMs} ms`,
    );
    out.push(`insert into public.exercise_expected_results (exercise_id, dataset_version, columns, rows, row_count)
values ((select id from public.exercises where slug = ${q(ex.slug)}), ${ex.dataset.version}, ${q(JSON.stringify(reference.columns))}::jsonb, ${q(JSON.stringify(reference.rows))}::jsonb, ${reference.rowCount})
on conflict (exercise_id) do update set dataset_version = excluded.dataset_version, columns = excluded.columns, rows = excluded.rows, row_count = excluded.row_count, computed_at = now();`);
  }

  for (const p of instances.values()) await (await p).close();

  if (failures) {
    console.error(`content:verify — FAILED (${failures} problem(s), ${verified} verified)`);
    process.exit(1);
  }
  if (!only) {
    out.push("commit;");
    writeFileSync(
      join(process.cwd(), "supabase", "seed", "0003_expected_results.sql"),
      out.join("\n\n") + "\n",
    );
  }
  console.log(
    `content:verify — OK (${verified} exercise(s) verified${only ? "" : ", expected results written"}).`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
