/**
 * Generates the curated avatar set (D-14): 24 abstract geometric compositions in the brand
 * palette, gender-neutral and culture-neutral. Deterministic: same input → same SVG.
 * Output: public/avatars/<slug>.svg and supabase/seed/0001_avatars.sql
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const palettes = [
  { name: "indigo", bg: "#2B4FE0", fg: "#FFFFFF", accent: "#F2652E" },
  { name: "coral", bg: "#F2652E", fg: "#FFFFFF", accent: "#2B4FE0" },
  { name: "teal", bg: "#1C8A5A", fg: "#FFFFFF", accent: "#F0B35A" },
  { name: "slate", bg: "#1E2533", fg: "#E8ECF3", accent: "#7C93FF" },
] as const;

type Shape = { name: string; label: string; draw: (fg: string, accent: string) => string };

const shapes: Shape[] = [
  {
    name: "grid",
    label: "Cuadrícula de cuatro celdas",
    draw: (fg, ac) =>
      `<rect x="22" y="22" width="24" height="24" rx="4" fill="${fg}"/><rect x="54" y="22" width="24" height="24" rx="4" fill="${fg}" opacity=".55"/><rect x="22" y="54" width="24" height="24" rx="4" fill="${fg}" opacity=".55"/><rect x="54" y="54" width="24" height="24" rx="4" fill="${ac}"/>`,
  },
  {
    name: "orbit",
    label: "Círculo con órbita",
    draw: (fg, ac) =>
      `<circle cx="50" cy="50" r="18" fill="${fg}"/><circle cx="50" cy="50" r="30" fill="none" stroke="${fg}" stroke-width="3" opacity=".5"/><circle cx="76" cy="38" r="6" fill="${ac}"/>`,
  },
  {
    name: "bars",
    label: "Barras ascendentes",
    draw: (fg, ac) =>
      `<rect x="22" y="58" width="12" height="20" rx="3" fill="${fg}" opacity=".6"/><rect x="40" y="44" width="12" height="34" rx="3" fill="${fg}" opacity=".8"/><rect x="58" y="30" width="12" height="48" rx="3" fill="${fg}"/><circle cx="64" cy="22" r="5" fill="${ac}"/>`,
  },
  {
    name: "triangle",
    label: "Triángulo con punto",
    draw: (fg, ac) =>
      `<polygon points="50,22 78,74 22,74" fill="${fg}"/><circle cx="50" cy="56" r="7" fill="${ac}"/>`,
  },
  {
    name: "wave",
    label: "Onda con nodo",
    draw: (fg, ac) =>
      `<path d="M18 58 C 30 38, 42 38, 50 58 S 70 78, 82 58" fill="none" stroke="${fg}" stroke-width="7" stroke-linecap="round"/><circle cx="50" cy="58" r="7" fill="${ac}"/>`,
  },
  {
    name: "hex",
    label: "Hexágono con núcleo",
    draw: (fg, ac) =>
      `<polygon points="50,20 76,35 76,65 50,80 24,65 24,35" fill="${fg}"/><polygon points="50,38 60,44 60,56 50,62 40,56 40,44" fill="${ac}"/>`,
  },
];

const outDir = join(process.cwd(), "public", "avatars");
mkdirSync(outDir, { recursive: true });

const rows: string[] = [];
let order = 0;
for (const shape of shapes) {
  for (const palette of palettes) {
    const slug = `${shape.name}-${palette.name}`;
    const alt = `${shape.label}, fondo ${palette.name}`;
    const svg =
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" role="img" aria-label="${alt}">` +
      `<rect width="100" height="100" rx="50" fill="${palette.bg}"/>` +
      shape.draw(palette.fg, palette.accent) +
      `</svg>\n`;
    writeFileSync(join(outDir, `${slug}.svg`), svg);
    rows.push(
      `  ('${slug}', '/avatars/${slug}.svg', '${alt.replace(/'/g, "''")}', true, ${order++})`,
    );
  }
}

const seed =
  `-- Generated by scripts/generate-avatars.ts. Do not edit by hand.\n` +
  `insert into public.avatars (slug, image_path, alt_text, is_active, sort_order) values\n` +
  rows.join(",\n") +
  `\non conflict (slug) do update set image_path = excluded.image_path, alt_text = excluded.alt_text, sort_order = excluded.sort_order;\n`;
mkdirSync(join(process.cwd(), "supabase", "seed"), { recursive: true });
writeFileSync(join(process.cwd(), "supabase", "seed", "0001_avatars.sql"), seed);
console.log(`generated ${rows.length} avatars`);
